# Generated by Django 3.2.9 on 2021-12-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, choices=[('finished', 'finished'), ('upcomming', 'upcomming'), ('ongoing', 'ongoing')], max_length=20, null=True),
        ),
    ]
