# Generated by Django 3.2.6 on 2021-12-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_appointment_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date_time',
            new_name='date_time_end',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date_time_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
