# Generated by Django 3.2.6 on 2021-12-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20211227_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='prescription',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions/%Y/%m/%d'),
        ),
    ]
