# Generated by Django 3.2.9 on 2021-11-18 16:33

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=8)),
                ('contact', models.CharField(max_length=12)),
                ('dob', models.DateField()),
                ('speciality', models.CharField(choices=[('Podiatrist', 'Podiatrist'), ('General', 'General'), ('Pediatrician', 'Pediatrician'), ('Endocrinologist', 'Endocrinologist'), ('NeuroLogist', 'Neurologist'), ('Rheumatologist', 'Rheumatologist'), ('Alergist', 'Allergist'), ('Psychiatrist', 'Psychiatrist')], max_length=20)),
                ('bio', models.TextField(max_length=800, null=True)),
                ('yoe', models.IntegerField()),
                ('charge', models.DecimalField(decimal_places=2, max_digits=7, max_length=10)),
                ('sun_start', models.TimeField()),
                ('sun_end', models.TimeField()),
                ('mon_start', models.TimeField()),
                ('mon_end', models.TimeField()),
                ('tue_start', models.TimeField()),
                ('tue_end', models.TimeField()),
                ('wed_start', models.TimeField()),
                ('wed_end', models.TimeField()),
                ('thu_start', models.TimeField()),
                ('thu_end', models.TimeField()),
                ('fri_start', models.TimeField()),
                ('fri_end', models.TimeField()),
                ('sat_start', models.TimeField()),
                ('sat_end', models.TimeField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
