# Generated by Django 3.2.6 on 2021-12-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211118_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='bio',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
    ]
