# Generated by Django 3.2.6 on 2021-12-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211210_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='paypal',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
    ]
