# Generated by Django 3.2.6 on 2021-12-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_doctor_paypal'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_images/'),
        ),
    ]
