# Generated by Django 4.0.4 on 2022-05-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='heart.jpg', upload_to='blogs/%Y/%m/%d/'),
        ),
    ]
