# Generated by Django 3.2.9 on 2022-05-20 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_doctor_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(default='heart.jpg', upload_to='blogs/%Y/%m/%d/')),
                ('blog', models.TextField(max_length=6500)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor')),
            ],
        ),
    ]
